"""Deterministic cross-domain artifact generation for Limen profiles."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from .schema import PartnerProfile


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n"


def _macro(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def _float(value: float) -> str:
    return f"{value:.6f}F"


@dataclass(frozen=True)
class CompilationArtifacts:
    """Generated outputs from one validated profile."""

    profile_id: str
    files: Mapping[str, str]

    def write(self, output_dir: Path) -> tuple[Path, ...]:
        output_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []
        for name in sorted(self.files):
            path = output_dir / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(self.files[name], encoding="utf-8", newline="\n")
            written.append(path)
        return tuple(written)


class ProfileCompiler:
    """Compile one validated profile into simulation, firmware, RTL, and test targets.

    Generated C and Verilog are reference artifacts for review and integration;
    they are not a claim of MISRA certification, RTL verification, or production
    hardware readiness.
    """

    def compile(self, profile: PartnerProfile) -> CompilationArtifacts:
        return CompilationArtifacts(
            profile_id=profile.profile_id,
            files={
                "simulation_profile.json": self._simulation(profile),
                "firmware_profile.h": self._firmware_header(profile),
                "rtl_profile.vh": self._rtl_parameters(profile),
                "fault_test_vectors.json": self._test_vectors(profile),
            },
        )

    def _simulation(self, profile: PartnerProfile) -> str:
        payload = {
            "target": "simulation",
            "profile": profile.to_mapping(),
            "runtime": {
                "quality_gate": "confidence_coupled_safety_envelope",
                "unknown_intent_action": "safe_halt",
                "hardware_supervisor": "enabled",
            },
        }
        return _canonical_json(payload)

    def _firmware_header(self, profile: PartnerProfile) -> str:
        tag = _macro(profile.profile_id)
        actuator = profile.actuator
        lines = [
            "/* Generated by limen.profile. Reference artifact; review before target integration. */",
            "/* No certification or complete MISRA-C claim is made by this generator. */",
            f"#ifndef LIMEN_PROFILE_{tag}_H",
            f"#define LIMEN_PROFILE_{tag}_H",
            "",
            "#include <stdint.h>",
            "",
            "#define LIMEN_PROFILE_SCHEMA_MAJOR (1U)",
            f"#define LIMEN_PROFILE_SENSOR_COUNT ({len(profile.sensors)}U)",
            f"#define LIMEN_PROFILE_INTENT_COUNT ({len(profile.intent_classes)}U)",
            f"#define LIMEN_PROFILE_MAX_TORQUE_NM ({_float(actuator.max_torque_nm)})",
            f"#define LIMEN_PROFILE_MAX_VELOCITY_RAD_S ({_float(actuator.max_velocity_rad_s)})",
            "",
            "typedef struct",
            "{",
            "    float max_torque_nm;",
            "    float max_velocity_rad_s;",
            "    float position_min_rad;",
            "    float position_max_rad;",
            "} limen_actuator_limits_t;",
            "",
            "static const limen_actuator_limits_t limen_actuator_limits =",
            "{",
            f"    {_float(actuator.max_torque_nm)},",
            f"    {_float(actuator.max_velocity_rad_s)},",
            f"    {_float(actuator.position_min_rad)},",
            f"    {_float(actuator.position_max_rad)}",
            "};",
            "",
            f"#endif /* LIMEN_PROFILE_{tag}_H */",
            "",
        ]
        return "\n".join(lines)

    def _rtl_parameters(self, profile: PartnerProfile) -> str:
        tag = _macro(profile.profile_id)
        actuator = profile.actuator
        torque_mnm = round(actuator.max_torque_nm * 1000.0)
        velocity_urad_s = round(actuator.max_velocity_rad_s * 1_000_000.0)
        return "\n".join(
            [
                "// Generated by limen.profile. Reference parameters; not verified RTL.",
                f"// Profile: {profile.profile_id}",
                f"localparam integer LIMEN_{tag}_SENSOR_COUNT = {len(profile.sensors)};",
                f"localparam integer LIMEN_{tag}_INTENT_COUNT = {len(profile.intent_classes)};",
                f"localparam integer LIMEN_{tag}_MAX_TORQUE_MNM = {torque_mnm};",
                f"localparam integer LIMEN_{tag}_MAX_VELOCITY_URAD_S = {velocity_urad_s};",
                "",
            ]
        )

    def _test_vectors(self, profile: PartnerProfile) -> str:
        vectors = [
            {
                "id": f"sensor_{path.sensor}_failure",
                "fault": {"sensor": path.sensor, "condition": "disconnect"},
                "expected_action": path.action,
            }
            for path in profile.fault_paths
        ]
        vectors.extend(
            [
                {
                    "id": "actuator_torque_over_limit",
                    "fault": {
                        "actuator": profile.actuator.name,
                        "torque_nm": profile.actuator.max_torque_nm + 1.0,
                    },
                    "expected_action": "safe_halt",
                },
                {
                    "id": "actuator_velocity_over_limit",
                    "fault": {
                        "actuator": profile.actuator.name,
                        "velocity_rad_s": profile.actuator.max_velocity_rad_s + 1.0,
                    },
                    "expected_action": "safe_halt",
                },
            ]
        )
        return _canonical_json({"profile_id": profile.profile_id, "vectors": vectors})
